### ISSUE TITLE
Proposal: rename the nodejs/iojs-ru WG to nodejs/nodejs-ru

### ISSUE THREAD

**Issue by srl295** [nodejs/nodejs-ru#111]
Dear members of the io.js Russian WG `iojs-ru`

It is proposed to rename this repo to:

   [nodejs/nodejs-ru](https://github.com/nodejs/nodejs-ru/)

As part of the io.js and node.js convergence, node.js releases are now based on the codebase and user base of the converged node.js and io.js communities. A number of the resources and repositories have already been renamed.
In the absence of objections or other discussion, this rename will occur on or after [Oct 28, 2015](http://time.is/1200AM_28_Oct_2015_in_GMT?iojs-rename)

However, active language working groups should take ownership of this issue and discuss/dispose of it according to their own processes.

For more information or to discuss the overall issue, please see and comment on https://github.com/nodejs/node/issues/2525

This statement was authorized by the Node.js TSC

Cc: @nodejs/iojs-ru

**Comment by sidorares** [comment]
Are we going to rename @nodejs/iojs-ru team as well? ( no objections from me, :+1: )

**Comment by YuriSolovyov** [comment]
+1 :+1:

**Comment by srl295** [comment]
Done.
